### ISSUE TITLE
Failed to install - solution

### ISSUE THREAD

**Issue by JulianMutz** [gmelloni/interactionRCS#1]
The installation worked fine in this environment

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS  10.16

But I encountered the below error when trying to install the package elsewhere

devtools::install_github("https://github.com/gmelloni/interactionRCS.git")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

The latter issue was resolved by using install_git() instead of install_github()

devtools::install_git("https://github.com/gmelloni/interactionRCS.git")

Not sure why - posting this in case it is useful for anyone else

**Comment by gmelloni** [comment]
Adding it to the README, thanks!
