### ISSUE TITLE
P value?

### ISSUE THREAD

**Issue by fedenichetti** [gmelloni/interactionRCS#2]
Hi there, question from an ignorant: what is the correct pvalue of a coxph/cph model with an interaction term? Is there a way to get it with the interactionRCS package?
Thanks!

**Comment by gmelloni** [comment]
Ciao Fede,

sorry for getting back to you so late! P-values and splines are generally not happy campers together but if you need to report it for an interaction model I would suggest to report the pvalue of the simple interaction term. Let's say you have a model like:
surv(death) ~ age*bmi

it will expand into
surv(death) ~ age + bmi + age:bmi

the pvalue of the age:bmi term is what you are looking for!

Thanks!
