### ISSUE TITLE
Is it possible to use inEST function to generate RR and plot a RCS using plotINT?

### ISSUE THREAD

**Issue by Harvey166** [gmelloni/interactionRCS#6]
Hi Giorgio !

Thank you for your brillant work! Currently I am confronted with a tricky problem, as you know poisson regression model is avaliable in rms package, more specially, the **Glm** function can be used to construct a poisson regression model, but when I used **inEST** to generate rate ratio, error occured, saying “glm or Glm not of family gaussian nor binomial“ . So I wonder is it possible to use **inEST** to generate RR from poissson regression and then plot a RCS? If not, do you have any idea how I can solve this problem or is there any other package can be used?

Thank you for your time

**Comment by gmelloni** [comment]
Hi Harvey

It's probably not too complicated to tinker with the code and skip the stop I set for glm models but I'll certainly add poisson to the list of available models in the next round of update (hope it's not too urgent, I am on vacation)

Thank you!

Best,
Giorgio

________________________________
